const URL = 'http://localhost:8888/wp-json/wp/v2/'
export const WP_PAGES = URL + 'pages'
export const WP_POSTS = URL + 'posts?per_page=100'
export const WP_CONTENTCARDS = URL + 'posts?filter[category_name]=contentcard'
export const WP_TABS = URL + 'posts?filter[category_name]=infotab'
export const WP_HERO = URL + 'posts?filter[category_name]=hero'
